import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/Provider/ReduxProvider";
import Container from "@/components/Container/Container";
import Navbar from "@/components/Navbar/Navbar";
import Html from "@/components/Theme/Html";
import ContextApi from "@/Provider/ContextApi";
import BackdropFilter from "@/components/backdrop/BackdropFilter";

const inter = Raleway({ subsets: ["cyrillic-ext"] });

export const metadata: Metadata = {
  title: "CodiTalk | Express Your Thoughts",
  description: "Generated by create next app",
  authors: [{ name: "Miyad", url: "https://dev-miyad.vercel.app/" }],
  category: "Blog",
  generator: "CodiTalk",
  applicationName: "CodiTalk",
  creator: "Mahamudul hasan Miyad",
  keywords: ["facebook", "twitter", "threads", "coditalk"],
  publisher: "CodiTalk",
  openGraph: {
    type: "website",
    title: "CodiTalk || Express Your Thoughts",
    locale: "en_IE",
    phoneNumbers: ["+880 187 904 2507"],
    url: "https://coditalk.vercel.app/",
    emails: ["mhmiyad6565@gmail.com"],
    siteName: "CodiTalk",
    description: "Express Your Thoughts",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProvider>
      <Html>
        <ContextApi>
          <body className={inter.className}>
            <Container>
              <BackdropFilter />
              <Navbar />
              <div className="max-w-2xl mx-auto ">{children}</div>
            </Container>
          </body>
        </ContextApi>
      </Html>
    </ReduxProvider>
  );
}
