import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/Provider/ReduxProvider";
import Container from "@/components/Container/Container";
import Navbar from "@/components/Navbar/Navbar";
import Html from "@/components/Theme/Html";
import ContextApi from "@/Provider/ContextApi";

const inter = Raleway({ subsets: ["cyrillic-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProvider>
      <Html>
        <ContextApi>
          <body className={inter.className}>
            <Container>
              <Navbar />
              <div className="max-w-2xl mx-auto ">{children}</div>
            </Container>
          </body>
        </ContextApi>
      </Html>
    </ReduxProvider>
  );
}
