import React from "react";
import ProfileComp from "@/components/Profile/Profile";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Profile Page ",
  description: "Generated by create next app",
};
const ProfilePage = () => {
  return (
    <div className="relative w-full ">
      <ProfileComp />
    </div>
  );
};

export default ProfilePage;
